{{- if .Values.volume.persistentVolume.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: indexer-volume-{{ .Release.Name }}
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.persistentVolume.hostPath }}
    type: DirectoryOrCreate
{{- end }}