apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: indexer-status-service
  name: indexer-status-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: indexer-status-service
status:
  loadBalancer: {}
