apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: indexer-gateway
  name: indexer-gateway
spec:
  ports:
    - name: "4010"
      port: 4010
      targetPort: 8080
  selector:
    io.kompose.service: indexer-gateway
status:
  loadBalancer: {}
