apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: indexer
  name: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: indexer
    spec:
      containers:
        - args:
            - sh
            - -c
            - yarn db:bootstrap && yarn start:prod
          env:
            - name: BLOCK_HEIGHT
              value: "0"
            - name: DB_HOST
              value: {{ .Values.db_endpoint }}
            - name: DB_NAME
              value: indexer-db
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: REDIS_URI
              value: "redis://redis:6379/1"
            - name: BUNDLE_TYPES
              value: /config/typesBundle.json
            - name: WORKERS_NUMBER
              value: "1"
            - name: WS_PROVIDER_ENDPOINT_URI
              value: {{ .Values.ws_endpoint }}
          image: subsquid/hydra-indexer:5
          name: indexer
          resources: {}
          volumeMounts:
            - mountPath: /config/typesBundle.json
              name: indexer-config
              subPath: typesBundle.json
      volumes:
        - name: indexer-config
          configMap:
            name: indexer-config
      restartPolicy: Always
status: {}
