apiVersion: v1
data:
  typesBundle.json: "{\r\n  \"spec\": {\r\n    \"polkadot\": [\r\n      {\r\n        \"minmax\":
    [\r\n          0,\r\n          12\r\n        ],\r\n        \"types\": {\r\n          \"CompactAssignments\":
    \"CompactAssignmentsTo257\",\r\n          \"RawSolution\": \"RawSolutionWith16\",\r\n
    \         \"Keys\": \"SessionKeys5\",\r\n          \"ProxyType\": {\r\n            \"_enum\":
    {\r\n              \"Any\": 0,\r\n              \"NonTransfer\": 1,\r\n              \"Governance\":
    2,\r\n              \"Staking\": 3,\r\n              \"UnusedSudoBalances\": 4,\r\n
    \             \"IdentityJudgement\": 5,\r\n              \"CancelProxy\": 6,\r\n
    \             \"Auction\": 7\r\n            }\r\n          },\r\n          \"AccountInfo\":
    \"AccountInfoWithRefCount\",\r\n          \"Address\": \"AccountId\",\r\n          \"LookupSource\":
    \"AccountId\",\r\n          \"ValidatorPrefs\": \"ValidatorPrefsWithCommission\",\r\n
    \         \"OpenTip\": \"OpenTipTo225\",\r\n          \"RefCount\": \"RefCountTo259\"\r\n
    \       }\r\n      },\r\n      {\r\n        \"minmax\": [\r\n          13,\r\n
    \         22\r\n        ],\r\n        \"types\": {\r\n          \"CompactAssignments\":
    \"CompactAssignmentsTo257\",\r\n          \"RawSolution\": \"RawSolutionWith16\",\r\n
    \         \"Keys\": \"SessionKeys5\",\r\n          \"ProxyType\": {\r\n            \"_enum\":
    {\r\n              \"Any\": 0,\r\n              \"NonTransfer\": 1,\r\n              \"Governance\":
    2,\r\n              \"Staking\": 3,\r\n              \"UnusedSudoBalances\": 4,\r\n
    \             \"IdentityJudgement\": 5,\r\n              \"CancelProxy\": 6,\r\n
    \             \"Auction\": 7\r\n            }\r\n          },\r\n          \"AccountInfo\":
    \"AccountInfoWithRefCount\",\r\n          \"Address\": \"AccountId\",\r\n          \"LookupSource\":
    \"AccountId\",\r\n          \"ValidatorPrefs\": \"ValidatorPrefsWithCommission\",\r\n
    \         \"RefCount\": \"RefCountTo259\"\r\n        }\r\n      },\r\n      {\r\n
    \       \"minmax\": [\r\n          23,\r\n          24\r\n        ],\r\n        \"types\":
    {\r\n          \"CompactAssignments\": \"CompactAssignmentsWith16\",\r\n          \"RawSolution\":
    \"RawSolutionWith16\",\r\n          \"Keys\": \"SessionKeys5\",\r\n          \"ProxyType\":
    {\r\n            \"_enum\": {\r\n              \"Any\": 0,\r\n              \"NonTransfer\":
    1,\r\n              \"Governance\": 2,\r\n              \"Staking\": 3,\r\n              \"UnusedSudoBalances\":
    4,\r\n              \"IdentityJudgement\": 5,\r\n              \"CancelProxy\":
    6,\r\n              \"Auction\": 7\r\n            }\r\n          },\r\n          \"AccountInfo\":
    \"AccountInfoWithRefCount\",\r\n          \"Address\": \"AccountId\",\r\n          \"LookupSource\":
    \"AccountId\",\r\n          \"ValidatorPrefs\": \"ValidatorPrefsWithCommission\",\r\n
    \         \"RefCount\": \"RefCountTo259\"\r\n        }\r\n      },\r\n      {\r\n
    \       \"minmax\": [\r\n          25,\r\n          27\r\n        ],\r\n        \"types\":
    {\r\n          \"CompactAssignments\": \"CompactAssignmentsWith16\",\r\n          \"RawSolution\":
    \"RawSolutionWith16\",\r\n          \"Keys\": \"SessionKeys5\",\r\n          \"ProxyType\":
    {\r\n            \"_enum\": {\r\n              \"Any\": 0,\r\n              \"NonTransfer\":
    1,\r\n              \"Governance\": 2,\r\n              \"Staking\": 3,\r\n              \"UnusedSudoBalances\":
    4,\r\n              \"IdentityJudgement\": 5,\r\n              \"CancelProxy\":
    6,\r\n              \"Auction\": 7\r\n            }\r\n          },\r\n          \"AccountInfo\":
    \"AccountInfoWithRefCount\",\r\n          \"Address\": \"AccountId\",\r\n          \"LookupSource\":
    \"AccountId\",\r\n          \"ValidatorPrefs\": \"ValidatorPrefsWithCommission\"\r\n
    \       }\r\n      },\r\n      {\r\n        \"minmax\": [\r\n          28,\r\n
    \         29\r\n        ],\r\n        \"types\": {\r\n          \"CompactAssignments\":
    \"CompactAssignmentsWith16\",\r\n          \"RawSolution\": \"RawSolutionWith16\",\r\n
    \         \"Keys\": \"SessionKeys6\",\r\n          \"ProxyType\": {\r\n            \"_enum\":
    {\r\n              \"Any\": 0,\r\n              \"NonTransfer\": 1,\r\n              \"Governance\":
    2,\r\n              \"Staking\": 3,\r\n              \"UnusedSudoBalances\": 4,\r\n
    \             \"IdentityJudgement\": 5,\r\n              \"CancelProxy\": 6,\r\n
    \             \"Auction\": 7\r\n            }\r\n          },\r\n          \"AccountInfo\":
    \"AccountInfoWithDualRefCount\"\r\n        }\r\n      },\r\n      {\r\n        \"minmax\":
    [\r\n          30,\r\n          9109\r\n        ],\r\n        \"types\": {\r\n
    \         \"CompactAssignments\": \"CompactAssignmentsWith16\",\r\n          \"RawSolution\":
    \"RawSolutionWith16\",\r\n          \"Keys\": \"SessionKeys6\",\r\n          \"ProxyType\":
    {\r\n            \"_enum\": {\r\n              \"Any\": 0,\r\n              \"NonTransfer\":
    1,\r\n              \"Governance\": 2,\r\n              \"Staking\": 3,\r\n              \"UnusedSudoBalances\":
    4,\r\n              \"IdentityJudgement\": 5,\r\n              \"CancelProxy\":
    6,\r\n              \"Auction\": 7\r\n            }\r\n          }\r\n        }\r\n
    \     },\r\n      {\r\n        \"minmax\": [\r\n          9110,\r\n          null\r\n
    \       ],\r\n        \"types\": {}\r\n      }\r\n    ]\r\n  }\r\n}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: indexer-config
